services:
  api-product:
    container_name: api-product
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "api-product:1.0.0"
    logging:
      options:
        max-size: "1m"
    depends_on:
      - postgres_ol
    environment:
      - DB_CONNECTION_URI=postgresql://postgres:isro@postgres_ol:5432/postgres?sslmode=disable
      - APP_PORT=4000
    ports:
      - 4000:4000
    volumes:
      - .:/app
    networks:
      - ol_network

  postgres_ol:
    container_name: postgres_ol
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=isro
      - POSTGRES_DB=database
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
        read_only: false
    networks:
      - ol_network

volumes:
  postgres_volume:
    name: postgres_volume

networks:
  ol_network:
    name: ol_network